-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MIPS_tester IS
   PORT( 
      alu_result_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      Branch_ctrl_o    : IN     STD_LOGIC;
      instruction_top_o: IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      MemWrite_ctrl_o  : IN     STD_LOGIC;
      pc_o             : IN     STD_LOGIC_VECTOR ( 9 DOWNTO 0 );
      RegWrite_ctrl_o  : IN     STD_LOGIC;
      Zero_o           : IN     STD_LOGIC;
      read_data1_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      read_data2_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      write_data_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      mclk_cnt_o       : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      inst_cnt_o       : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      STCNT_o          : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      FHCNT_o          : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      ST_trigger       : IN     STD_LOGIC;
      clk_i            : OUT    STD_LOGIC;
	  ena			   : OUT    STD_LOGIC;
      rst_i            : OUT    STD_LOGIC;
      BPADDR_i         : OUT    STD_LOGIC_VECTOR ( 7 DOWNTO 0 )
   );

-- Declarations

END MIPS_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MIPS_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 10000000 ns;
   clk_i <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   ena	 <= '1';
   rst_i <= mw_U_1pulse;
   BPADDR_i <= "00000000"; -- Default breakpoint address
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '1' AFTER 20 ns,
         '0' AFTER 120 ns;
      WAIT;
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.

END struct;
