-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE work.aux_package.ALL;

LIBRARY work;

ENTITY MIPS_tb_struct IS
-- Declarations
END MIPS_tb_struct;

ARCHITECTURE struct OF MIPS_tb_struct IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alu_result_o     : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL Branch_ctrl_o    : STD_LOGIC;
   SIGNAL instruction_top_o: STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL MemWrite_ctrl_o  : STD_LOGIC;
   SIGNAL pc_o             : STD_LOGIC_VECTOR( 9 DOWNTO 0 );
   SIGNAL RegWrite_ctrl_o  : STD_LOGIC;
   SIGNAL Zero_o           : STD_LOGIC;
   SIGNAL clk_i            : STD_LOGIC;
   SIGNAL read_data1_o     : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL read_data2_o     : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL rst_i            : STD_LOGIC;
   SIGNAL write_data_o     : STD_LOGIC_VECTOR( 31 DOWNTO 0 );
   SIGNAL mclk_cnt_o       : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL inst_cnt_o       : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL STCNT_o          : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL FHCNT_o          : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL BPADDR_i         : STD_LOGIC_VECTOR(7 DOWNTO 0);
   SIGNAL ST_trigger       : STD_LOGIC;
   SIGNAL ena              : STD_LOGIC;
   


   -- Component Declarations
   COMPONENT MIPS
	GENERIC ( 
		WORD_GRANULARITY : boolean 	:= True;
	    MODELSIM : integer 			:= 1;
		DATA_BUS_WIDTH : integer 	:= 32;
		ITCM_ADDR_WIDTH : integer 	:= 10;
		DTCM_ADDR_WIDTH : integer 	:= 10;
		PC_WIDTH : integer 			:= 10;
		FUNCT_WIDTH : integer 		:= 6;
		DATA_WORDS_NUM : integer 	:= 1024;
		CLK_CNT_WIDTH : integer 	:= 16;
		INST_CNT_WIDTH : integer 	:= 16;
		SIM : BOOLEAN := TRUE);
	PORT( 
		rst_i, clk_i, ena					: IN 	STD_LOGIC; 
		-- Output important signals to pins for easy display in Simulator
		pc_o									: OUT  STD_LOGIC_VECTOR( 9 DOWNTO 0 );
		alu_result_o 		:OUT	STD_LOGIC_VECTOR(DATA_BUS_WIDTH-1 DOWNTO 0);
		read_data1_o 		:OUT	STD_LOGIC_VECTOR(DATA_BUS_WIDTH-1 DOWNTO 0);
		read_data2_o 		:OUT	STD_LOGIC_VECTOR(DATA_BUS_WIDTH-1 DOWNTO 0);
		write_data_o		:OUT	STD_LOGIC_VECTOR(DATA_BUS_WIDTH-1 DOWNTO 0);
		instruction_top_o	:OUT	STD_LOGIC_VECTOR(DATA_BUS_WIDTH-1 DOWNTO 0);
		Branch_ctrl_o		:OUT 	STD_LOGIC;
		Zero_o				:OUT 	STD_LOGIC; 
		MemWrite_ctrl_o		:OUT 	STD_LOGIC;
		RegWrite_ctrl_o		:OUT 	STD_LOGIC;
		mclk_cnt_o			:OUT	STD_LOGIC_VECTOR(CLK_CNT_WIDTH-1 DOWNTO 0);
		inst_cnt_o 			:OUT	STD_LOGIC_VECTOR(INST_CNT_WIDTH-1 DOWNTO 0);
		STCNT_o 								: OUT  STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		FHCNT_o								: OUT  STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		BPADDR_i							: IN  STD_LOGIC_VECTOR( 7 DOWNTO 0 );
		ST_trigger							: OUT  STD_LOGIC
		);
	END 	COMPONENT;
   COMPONENT MIPS_tester
   PORT (
      alu_result_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      Branch_ctrl_o    : IN     STD_LOGIC ;
      instruction_top_o: IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      MemWrite_ctrl_o  : IN     STD_LOGIC ;
      pc_o             : IN     STD_LOGIC_VECTOR ( 9 DOWNTO 0 );
      RegWrite_ctrl_o  : IN     STD_LOGIC ;
      Zero_o           : IN     STD_LOGIC ;
      read_data1_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      read_data2_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      write_data_o     : IN     STD_LOGIC_VECTOR ( 31 DOWNTO 0 );
      mclk_cnt_o       : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      inst_cnt_o       : IN     STD_LOGIC_VECTOR ( 15 DOWNTO 0 );
      STCNT_o          : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      FHCNT_o          : IN     STD_LOGIC_VECTOR ( 7 DOWNTO 0 );
      ST_trigger       : IN     STD_LOGIC ;
      clk_i            : OUT    STD_LOGIC ;
	  ena			   : OUT    STD_LOGIC;
      rst_i            : OUT    STD_LOGIC ;
      BPADDR_i         : OUT    STD_LOGIC_VECTOR ( 7 DOWNTO 0 )
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MIPS USE ENTITY work.mips;
   FOR ALL : MIPS_tester USE ENTITY work.mips_tester;
   -- pragma synthesis_on


BEGIN


   -- Instance port mappings.
   U_0 : MIPS
	  GENERIC MAP (
		 WORD_GRANULARITY => True,
		 MODELSIM => 1,
		 DATA_BUS_WIDTH => 32,
		 ITCM_ADDR_WIDTH => 10,
		 DTCM_ADDR_WIDTH => 10,
		 PC_WIDTH => 10,
		 FUNCT_WIDTH => 6,
		 DATA_WORDS_NUM => 1024,
		 CLK_CNT_WIDTH => 16,
		 INST_CNT_WIDTH => 16,
		 SIM => TRUE ) 
      PORT MAP (
         rst_i            => rst_i,
         clk_i            => clk_i,
		   ena			    => ena,
         pc_o             => pc_o,
         alu_result_o     => alu_result_o,
         read_data1_o     => read_data1_o,
         read_data2_o     => read_data2_o,
         write_data_o     => write_data_o,
         instruction_top_o=> instruction_top_o,
         Branch_ctrl_o    => Branch_ctrl_o,
         Zero_o           => Zero_o,
         MemWrite_ctrl_o  => MemWrite_ctrl_o,
         RegWrite_ctrl_o  => RegWrite_ctrl_o,
         mclk_cnt_o       => mclk_cnt_o,
         inst_cnt_o       => inst_cnt_o,
         STCNT_o          => STCNT_o,
         FHCNT_o          => FHCNT_o,
         BPADDR_i         => BPADDR_i,
		 ST_trigger        => ST_trigger
      );
   U_1 : MIPS_tester
      PORT MAP (
         alu_result_o     => alu_result_o,
         Branch_ctrl_o    => Branch_ctrl_o,
         instruction_top_o=> instruction_top_o,
         MemWrite_ctrl_o  => MemWrite_ctrl_o,
         pc_o             => pc_o,
         RegWrite_ctrl_o  => RegWrite_ctrl_o,
         Zero_o           => Zero_o,
         read_data1_o     => read_data1_o,
         read_data2_o     => read_data2_o,
         write_data_o     => write_data_o,
         mclk_cnt_o       => mclk_cnt_o,
         inst_cnt_o       => inst_cnt_o,
         STCNT_o          => STCNT_o,
         FHCNT_o          => FHCNT_o,
         ST_trigger       => ST_trigger,
         clk_i            => clk_i,
		 ena			   => ena,
         rst_i            => rst_i,
         BPADDR_i         => BPADDR_i
      );

END struct;
